use anyhow::Result;

pub fn export_dotenv(
    configs: &[(String, String)],
    reveal_secrets: bool,
) -> Result<String> {
    let mut lines = Vec::new();

    lines.push("# generated by cascade".to_string());
    lines.push(String::new());

    for (key, value) in configs {
        let env_name = key_to_env_name(key);

        if value.starts_with("cc-enc:v1:") && !reveal_secrets {
            lines.push(format!("{}=${{{}}}", env_name, env_name));
        } else {
            lines.push(format!("{}=\"{}\"", env_name, escape_dotenv(value)));
        }
    }

    Ok(lines.join("\n"))
}

fn key_to_env_name(key: &str) -> String {
    key.replace('.', "_")
        .replace('-', "_")
        .to_uppercase()
}

fn escape_dotenv(value: &str) -> String {
    value
        .replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_export_dotenv() {
        let configs = vec![
            ("database.host".into(), "localhost".into()),
            ("database.port".into(), "5432".into()),
            ("api_key".into(), "cc-enc:v1:abc123".into()),
        ];

        let output = export_dotenv(&configs, false).unwrap();
        assert!(output.contains("DATABASE_HOST=\"localhost\""));
        assert!(output.contains("DATABASE_PORT=\"5432\""));
        assert!(output.contains("API_KEY=${API_KEY}"));
    }

    #[test]
    fn test_export_dotenv_reveal() {
        let configs = vec![
            ("api_key".into(), "cc-enc:v1:abc123".into()),
        ];

        let output = export_dotenv(&configs, true).unwrap();
        assert!(output.contains("API_KEY=\"cc-enc:v1:abc123\""));
    }
}
