use anyhow::Result;
use std::collections::HashMap;

pub fn export_yaml(
    configs: &[(String, String)], // (key, value)
    revision: u64,
) -> Result<String> {
    let mut doc = serde_yaml::Mapping::new();

    // Group configs by prefix
    let mut groups: HashMap<String, Vec<(&str, &str)>> = HashMap::new();

    for (key, value) in configs {
        let parts: Vec<&str> = key.split('.').collect();
        let group = if parts.len() > 1 {
            parts[0].to_string()
        } else {
            "root".to_string()
        };
        groups.entry(group).or_default().push((key, value));
    }

    // Build nested structure
    for (group, items) in &groups {
        if group == "root" {
            for (key, value) in items {
                let simple_key = key.split('.').last().unwrap_or(key);
                doc.insert(
                    serde_yaml::Value::String(simple_key.to_string()),
                    serde_yaml::Value::String(value.to_string()),
                );
            }
        } else {
            let mut sub_doc = serde_yaml::Mapping::new();
            for (key, value) in items {
                let simple_key = key.split('.').last().unwrap_or(key);
                sub_doc.insert(
                    serde_yaml::Value::String(simple_key.to_string()),
                    serde_yaml::Value::String(value.to_string()),
                );
            }
            doc.insert(
                serde_yaml::Value::String(group.clone()),
                serde_yaml::Value::Mapping(sub_doc),
            );
        }
    }

    let header = format!("# generated by cascade @ revision {}\n", revision);
    let content = serde_yaml::to_string(&doc)?;
    Ok(format!("{}{}", header, content))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_export_yaml() {
        let configs = vec![
            ("database.host".into(), "localhost".into()),
            ("database.port".into(), "5432".into()),
            ("redis.host".into(), "localhost".into()),
        ];

        let output = export_yaml(&configs, 1).unwrap();
        assert!(output.contains("# generated by cascade @ revision 1"));
        assert!(output.contains("database:"));
        assert!(output.contains("host: localhost"));
    }
}
